### ISSUE TITLE
Migrate entry upgrade scripts from tickbin-client

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/parser#13]

**Comment by jonotron** [comment]
We probably only need the map functions, the upgrader and upgrade command is specific to the command line client (I think)

**Comment by chadfawcett** [comment]
I think it will make sense to move the 'upgrader' along with the map functions. The 'upgrade command' however is specific to the command line client.

The upgrader should be able to be called from the web client, server, etc in order to upgrade the entries.

**Comment by chrisfosterelli** [comment]
Does this have anything to do with parsing though? Starting to feel like we are using this repository as a grab bag of things.

Abstracting it out is definitely a good idea, just not sure if here is the right place to put it.

**Comment by chadfawcett** [comment]
It has to do with the Entries.

**Comment by chadfawcett** [comment]
However, this issue came up when this repo was strictly for Entry parsing. I'm open to suggestions but I feel like creating a different repo for every different parser (especially the ones with a lot of overlap) is overkill. It's starting to feel like inheritance through packages.

**Comment by chrisfosterelli** [comment]
We should be careful to not create our own dependency hell, and I know we've been starting to feel that a little bit when doing maintenance. It's not that I'm necessarily for dividing things into a hundred packages or throwing everything into one, but that it should be intuitive where someone should go to look for something. 

In specific terms: We've already had some confusion on both mine and @jonotron's side about how `filter-parser` and `parser` are different, it took me a while to find `Entry` yesterday as I wasn't expecting it to be here, and I can already foresee it being very confusing that migration functions are stored in a library called `parser`. For us, we will eventually remember it but it could discourage contributions from the community if it isn't clear what is where and why.

Perhaps we just need some better repository naming (`tickbin/common`?). I'm definitely not sure what a perfect solution would be.

I think this relates to https://github.com/tickbin/filter-parser/issues/12

**Comment by jonotron** [comment]
Could we separate `Entry` into it's own repo which would include the upgraders? It seems a little odd that it's buried inside a parser library.

**Comment by chadfawcett** [comment]
Entries are created via parsing though. I guess it would be okay to separate the entry into a different repo as it is already a seperate module that relies on the parser. My hesitation comes from thinking it would be weird/annoying to have several repos for very similar things (filter-parser, parser, entry, timer, etc)

**Comment by jonotron** [comment]
I could see using `Entry` in other places where the parser isn't needed. e.g. a form that creates new entries

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
