### ISSUE TITLE
Migrate from shortID

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/parser#18]
@chadfawcett and I discovered that, due to a [subtle change](https://github.com/dylang/shortid/commit/ce664be16b8cb18ea938ecfa73a3195992c86315) in [shortId](https://github.com/dylang/shortid), all of the records before April have 9 character ID's and all of the records after April have 8 character ID's. 

This wasn't a breaking change because shortId only promises to return ID's _somewhere_ in the range of 7-14 characters. This kind of sucks for display purposes if we can't predict how long an ID will be, since we have to pad for the maximum of 14 characters which is actually quite rare.

ShortId also has a number of other limitations, such as not being able to have non-select-breaking characters like `-` and `_`. 

I don't have any great alternatives, but I wouldn't mind making one if need be. @jonotron thoughts?

**Comment by jonotron** [comment]
I'd prefer if we use an existing library to generate this ID and I'm not against doing what git does with hashes (does not guarantee uniqueness on short hashes). If nothing exists that works well, we can make one.

I like shortID. It's great for things like URLs, but maybe the wrong choice for our needs here.

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
