### ISSUE TITLE
`hashPattern` is no longer exposed

### ISSUE THREAD

**Issue by chrisfosterelli** [tickbin/parser#22]
Tickbin uses this, for now I will just hardcode it in tickbin but we may want to consider re-exposing it. It's also only a couple lines to duplicate and may not be the responsibility of the parser to provide this to Tickbin.

Thoughts?

**Comment by chadfawcett** [comment]
Yeah this should probably be re-exposed. I must have missed that it was still being used outside of the parsing. I could go either way on whether or not it's the job of the parser to supply it.

**Comment by jonotron** [comment]
For now I think we expose it. I think this ultimately belongs in a tags
module of some sort. Maybe `tagset`?

**Comment by chrisfosterelli** [comment]
Sounds good!
