### ISSUE TITLE
Dates not parsed out properly

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/parser#45]
1. `March 25 6h did some #stuff` gets parsed for the correct date and duration, but the `25` is left in the entry message: `25 did some #stuff`
2. `6h did some #stuff March 25` gets parsed for the wrong date, but gets the duration correct. Entry message results as: `did some #stuff March 25`

I am pretty sure it worked before #42 was merged in, but I didn't dive deep enough into the regex implemented in `durationRefiner` to be sure.

**Comment by chadfawcett** [comment]
@mccullochk Do you want to take this on in the near future, as I think it's related to #42? If not that's fine, I can take a crack at it.

**Comment by mccullochk** [comment]
Yes I can look into this!

**Comment by mccullochk** [comment]
@chadfawcett, I've pull down the parser at the point in time directly before I made any changes to it (at https://github.com/tickbin/parser/tree/af6d9fa02698eb4e3c0cdda820404db3154605d9) and it still seems to have the same behaviour you've described. Therefore I think your assumption that the issue was caused in #42 is incorrect but I can still look into finding a solution.

**Comment by mccullochk** [comment]
Though this doesn't make sense because I managed to enter a #stat in February without having the date get left in the message and now we can't and the only changes since then are #42 and #43.

**Comment by mccullochk** [comment]
Oh actually these might be separate issues. The latter is fixed when we revert to pre #42 and #43. I'm going to open up another issue for that then.

**Comment by chadfawcett** [comment]
Yeah, I used to enter mine with the date at the end of the message to get around the bug. So for my example 1 above, it wasn't introduced in #42, but instead I just became aware of it because I thought dates could go at the beginning now?

You mentioned in #35 that you updated `chrono-node`, this could be where the difference is coming from.

**Comment by mccullochk** [comment]
Hmm.. In #42 I was dealing specifically with implied dates with proceeding decimal numbers.
