### ISSUE TITLE
Entries that have IDs starting with an underscore fail to save

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/parser#54]
**Steps to reproduce**: Occurs very intermittently when creating an entry (ie `9:15-11:15am #bug fixing`).

![screen shot 2019-02-25 at 11 43 01 am](https://user-images.githubusercontent.com/3250463/53364580-f5967f00-38f3-11e9-80f5-f753d77fe8a5.png)

In the past I've randomly had entries display with the start and end time being the same. When refreshed, the entry no longer appeared. I thought this might have to do with tickbin thinking the entry was 0 minutes long, so it wouldn't display but was still saved. This past occurrence I wanted to make sure the entry wasn't persisted so I tried deleting it, but nothing happened. Opening the console revealed two issues:

1. The entry failed to save as the id started with an underscore (`_u6T-f-gS4`)
1. The entry failed to delete because it didn't actually exist (`404 not_found`)

<img width="835" alt="screen shot 2019-02-25 at 11 54 05 am" src="https://user-images.githubusercontent.com/3250463/53364703-3f7f6500-38f4-11e9-8bd6-7f2b87a73587.png">

**Comment by chrisfosterelli** [comment]
Closing this as this repository is no longer maintained
